const a_roster = [
    { name: "Adam Ziff", number: 18, year: "fr" },
    { name: "Alan Wong", number: 1, year: "so" },
    { name: "Alex Taylor-Lash", number: 9, year: "so" },
    { name: "Andrew Wang", number: 32, year: "sr" },
    { name: "Calvin Deng", number: 91, year: "gr" },
    { name: "Charles Coburn", number: 11, year: "sr" },
    { name: "Derek Poletti", number: 13, year: "fr" },
    { name: "Dylan Baroody", number: 37, year: "sr" },
    { name: "Erik Taylor-Lash", number: 8, year: "so" },
    { name: "Ethan Tyler", number: 44, year: "fr" },
    { name: "Jack Sullivan", number: 7, year: "fr" },
    { name: "Jake Waksbaum", number: 36, year: "jr" },
    { name: "Jason King", number: 99, year: "jr" },
    { name: "Julian Alvarez", number: 19, year: "fr" },
    { name: "Kapil Chandran", number: 14, year: "jr" },
    { name: "Max Land", number: 6, year: "so" },
    { name: "Nadeem Demian", number: 10, year: "sr" },
    { name: "Nate Moses", number: 55, year: "sr" },
    { name: "Nate Moore", number: 3, year: "fr" },
    { name: "Nick Nelsonwood", number: 33, year: "sr" },
    { name: "Noah Hastings", number: 42, year: "sr" },
    { name: "Patrick Chen", number: 28, year: "sr" },
    { name: "Rocco Amorosso", number: 17, year: "sr" },
    { name: "Sean Gai", number: 5, year: "jr" },
    { name: "Seho Young", number: 4, year: "sr" },
    { name: "Shamay Agaron", number: 12, year: "sr" },
    { name: "Steven Chien", number: 21, year: "jr" },
    { name: "Tim Feng", number: 00, year: "so" },
    { name: "Tom Colen", number: 16, year: "jr" },
    { name: "Victor Zhou", number: 27, year: "sr" },
    { name: "Yang Tu", number: 2, year: "jr" },
];

const a_captains = [
    "Charles Coburn",
    "Dylan Baroody",
    "Jake Waksbaum",
    "Victor Zhou",
];

const presidents = [
    "Alan Wong",
    "Tom Colen",
]

const social_chairs = [
    "Aaron Ballesian",
    "Daniel Chae",
    "Tim Feng",
    "Yang Tu"
]

const b_roster = [
    "Aaron Ballesian",
    "Aaron Litchblau",
    "Aditya Cowsik",
    "Alex Kaplan",
    "Andre Xiong",
    "Andrew Wang",
    "Andrew Goh",
    "Chris Chu",
    "Chris Evanko",
    "Dan McGee",
    "Daniel Chae",
    "Frank Li",
    "Jack Graham",
    "Jeffrey Sun",
    "Joe Puryear",
    "Jonah Vernejoul",
    "Josh Wang",
    "Juneseo Lee",
    "Matthew Maeder",
    "Pranav Rekapalli",
    "Ryan McCaffrey",
    "William Li",
    "Bryant Hall",
    "Luke Begley",
    "Arjun Guthal",
    "Evan Brandon",
    "Matthew Trotter",
    "Elijah Shina",
    "Liam Johansson",
    "Vignesh Panchanatham",
    "Perry Cate",
    "Elijah Pomerantz",
    "Kevin Feng",
    "Jackson Deitelzweig",
    "Brian Kang",
    "Son Do",
    "Andrew Larrieu",
    "Nishaad Khedkar",
    "Samuel Lee",
    "Vincent Yang",
    "Jared Rios",
    "Brendan Houle",
    "Ronnie Kihonge"
];

const b_captains = [
    "Andrew Goh",
    "Alex Kaplan",
    "Chris Chu",
    "Chris Evanko"
];